service: wildrydes-serverless

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  stage: dev
  #USAR XRAY
  tracing:
    apiGateway: true
    lambda: true
    
  iamRoleStatements: # Añade permisos a los de depecto
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
      Resource: !GetAtt DynamoTable.Arn
    - Effect: "Allow"
      Action:
       - "codedeploy:*"
      Resource:
       - "*"
      
plugins:
  - serverless-finch
  - serverless-plugin-aws-alerts
  - serverless-plugin-canary-deployments
  
custom:
  client:
    bucketName: ${self:service}-${self:provider.stage}-alan-cruz
    distributionFolder: website
  
  alerts:
    dashboards: true
    alarms:
      - functionThrottles
      - functionErrors
      - functionInvocations
      - functionDuration
  
functions:
  RequestUnicorn:
    handler: lambda_function/requestUnicorn.handler
    environment:
      dynamoTableName: ${self:service}-${self:provider.stage}
    events:
      - http:
          path: ride
          method: post
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-east-1:450939501754:userpool/us-east-1_hjci6HPMM
    
    deploymentSettings:
      type: Linear10PercentEvery1Minute
      alias: Live

package:
  exclude:
    - website/**
  
resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:service}-${self:provider.stage}
        AutoVerifiedAttributes:
          - email
        Schema:
          - Name: email
            Mutable: false
            Required: true
    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: WildRydesWebApp
        UserPoolId:
          Ref: CognitoUserPool
        GenerateSecret: false
    DynamoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}
        ProvisionedThroughput:
          ReadCapacityUnits: "5"
          WriteCapacityUnits: "5"
        AttributeDefinitions:
          - AttributeName: "RideId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "RideId"
            KeyType: "HASH"
  Outputs:
    UserPoolId:
      Value:
        Ref: CognitoUserPool
    UserPoolArn:
      Value: !GetAtt CognitoUserPool.Arn
    UserPoolClientId:
      Value:
        Ref: CognitoUserPoolClient